"""
write_audit_publish
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
import pendulum


default_args={
    "owner": "colethompson@comcast.net,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2023-09-11", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "colethompson@comcast.net": "mailto:colethompson@comcast.net",
        "Open in Cloud IDE": "https://cloud.astronomer.io/clmb05dcg000r01mx35j05puq/cloud-ide/clmb061c4000s01mxo9e2biw0/clmfe33un003401jugswkh5rz",
    },
)
def write_audit_publish():

dag_obj = write_audit_publish()
